sonar.projectKey=mazuk1_deepmem
sonar.organization=mazuk1
sonar.sources=deepmem,server
sonar.tests=tests
sonar.exclusions=deepmem/vendor/**,coverage.xml,tests/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
